project:
  type: website
  output-dir: docs
website:
  title: 许丽华 - 生态学硕士
  site-url: https://yourusername.github.io/repo-name/
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: education.qmd
        text: 教育背景
      - href: publications.qmd
        text: 科研成果
      - href: projects.qmd
        text: 项目经历
      - href: skills.qmd
        text: 专业技能
      - href: contact.qmd
        text: 联系方式

format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    code-fold: true
    code-overflow: wrap
